export const planets = [
  {
    nombre: 'Mercurio',
    diametro: 4879,
    masa: 3.3011e23,
    gravedad: 3.7,
    duracionDelDia: 4222.6,
    periodoOrbital: 88,
    distanciaDelSol: 57900000,
    temperatura: { minima: -173, maxima: 427 },
    atmosfera: {
      composicion: [
        { gas: 'Oxígeno (O₂)', porcentaje: 42 },
        { gas: 'Sodio (Na)', porcentaje: 29 },
        { gas: 'Hidrógeno (H₂)', porcentaje: 22 },
        { gas: 'Helio (He)', porcentaje: 6 },
      ],
    },
    lunas: 0,
    imagen: 'https://space-facts.com/wp-content/uploads/mercury-transparent.png',
  },
  {
    nombre: 'Venus',
    diametro: 12104,
    masa: 4.8675e24,
    gravedad: 8.87,
    duracionDelDia: 2802,
    periodoOrbital: 225,
    distanciaDelSol: 108200000,
    temperatura: { minima: 462, maxima: 462 },
    atmosfera: {
      composicion: [
        { gas: 'Dióxido de carbono (CO₂)', porcentaje: 96.5 },
        { gas: 'Nitrógeno (N₂)', porcentaje: 3.5 },
      ],
    },
    lunas: 0,
    imagen: 'https://space-facts.com/wp-content/uploads/venus-transparent.png',
  },
  {
    nombre: 'Tierra',
    diametro: 12742,
    masa: 5.97237e24,
    gravedad: 9.81,
    duracionDelDia: 24,
    periodoOrbital: 365.25,
    distanciaDelSol: 149600000,
    temperatura: { minima: -89.2, maxima: 56.7 },
    atmosfera: {
      composicion: [
        { gas: 'Nitrógeno (N₂)', porcentaje: 78 },
        { gas: 'Oxígeno (O₂)', porcentaje: 21 },
        { gas: 'Argón (Ar)', porcentaje: 0.93 },
        { gas: 'Dióxido de carbono (CO₂)', porcentaje: 0.04 },
      ],
    },
    lunas: 1,
    imagen: 'https://space-facts.com/wp-content/uploads/earth-transparent.png',
  },
  {
    nombre: 'Marte',
    diametro: 6779,
    masa: 6.4171e23,
    gravedad: 3.71,
    duracionDelDia: 24.6,
    periodoOrbital: 687,
    distanciaDelSol: 227900000,
    temperatura: { minima: -125, maxima: 20 },
    atmosfera: {
      composicion: [
        { gas: 'Dióxido de carbono (CO₂)', porcentaje: 95.32 },
        { gas: 'Nitrógeno (N₂)', porcentaje: 2.7 },
        { gas: 'Argón (Ar)', porcentaje: 1.6 },
      ],
    },
    lunas: 2,
    imagen: 'https://space-facts.com/wp-content/uploads/mars-transparent.png',
  },
  {
    nombre: 'Júpiter',
    diametro: 139820,
    masa: 1.8982e27,
    gravedad: 24.79,
    duracionDelDia: 9.9,
    periodoOrbital: 4333,
    distanciaDelSol: 778500000,
    temperatura: { minima: -108, maxima: -108 },
    atmosfera: {
      composicion: [
        { gas: 'Hidrógeno (H₂)', porcentaje: 89.8 },
        { gas: 'Helio (He)', porcentaje: 10.2 },
      ],
    },
    lunas: 79,
    imagen: 'https://space-facts.com/wp-content/uploads/jupiter-transparent.png',
  },
  {
    nombre: 'Saturno',
    diametro: 116460,
    masa: 5.6834e26,
    gravedad: 10.44,
    duracionDelDia: 10.7,
    periodoOrbital: 10759,
    distanciaDelSol: 1433000000,
    temperatura: { minima: -139, maxima: -139 },
    atmosfera: {
      composicion: [
        { gas: 'Hidrógeno (H₂)', porcentaje: 96.3 },
        { gas: 'Helio (He)', porcentaje: 3.25 },
      ],
    },
    lunas: 83,
    imagen: 'https://space-facts.com/wp-content/uploads/saturn-transparent.png',
  },
  {
    nombre: 'Urano',
    diametro: 50724,
    masa: 8.6810e25,
    gravedad: 8.69,
    duracionDelDia: 17.2,
    periodoOrbital: 30687,
    distanciaDelSol: 2871000000,
    temperatura: { minima: -224, maxima: -224 },
    atmosfera: {
      composicion: [
        { gas: 'Hidrógeno (H₂)', porcentaje: 82.5 },
        { gas: 'Helio (He)', porcentaje: 15.2 },
        { gas: 'Metano (CH₄)', porcentaje: 2.3 },
      ],
    },
    lunas: 27,
    imagen: 'https://space-facts.com/wp-content/uploads/uranus-transparent.png',
  },
  {
    nombre: 'Neptuno',
    diametro: 49244,
    masa: 1.02413e26,
    gravedad: 11.15,
    duracionDelDia: 16.1,
    periodoOrbital: 60190,
    distanciaDelSol: 4495000000,
    temperatura: { minima: -218, maxima: -218 },
    atmosfera: {
      composicion: [
        { gas: 'Hidrógeno (H₂)', porcentaje: 80 },
        { gas: 'Helio (He)', porcentaje: 19 },
        { gas: 'Metano (CH₄)', porcentaje: 1.5 },
      ],
    },
    lunas: 14,
    imagen: 'https://space-facts.com/wp-content/uploads/neptune-transparent.png',
  }
];
